# to update 
# docker-compose stop
# docker-compose pull
# docker-compose up -d

version: "3.3"

services:
  mongo:
    image: mongo:4.2.0
    networks:
      - ampnado
    ports:
      - 27017:27017

  amp:
    image: ampnadoamd:latest
    build: .
    environment:
      - AMP_PROGRAM_PATH=/usr/share/Ampnado
      - AMP_AMPDB_ADDR=mongodb://mongo:27017/maindb
      - AMP_VIEWSDB_ADDR=mongodb://mongo:27017/ampamdviewsDB
      - AMP_PICDB_ADDR=mongodb://mongo:27017/ampamdpicDB
      - AMP_SETUP=1
      - AMP_MEDIA_PATH=/usr/share/Ampnado/Music
      - AMP_HTTP_THUMBNAIL_DIR_PATH=/static/images/thumbnails
      - AMP_THUMBNAIL_DIR_PATH=/usr/share/Ampnado/static/images/thumbnails
      - AMP_NO_ART_PIC_PATH=/usr/share/Ampnado/static/images/noartpic.jpg
      - AMP_SERVER_ADDR=http://192.168.1.34
      - AMP_SERVER_PORT=6789
      - AMP_OFFSET_SIZE=45
      - AMP_USERNAME=admin
      - AMP_PASSWORD=ampnado

    networks:
      - ampnado
    ports:
      - 6789:6789
    volumes:
      - ampnadovol:/usr/share/Ampnado/Music/
      - ampnadopicvol:/usr/share/Ampnado/static/images/thumbnails
    depends_on:
      - mongo

networks:
  ampnado:

volumes:

  ampnadopicvol:
    driver: local
    driver_opts: 
      type: none
      device: /home/teresa/Ampnado-AMD-Docker-Data/picdata
      o: bind

  ampnadovol:
    driver: local
    driver_opts:
      type: none
#THIS NEEDS TO BE CHANGE TO THE CORRECT PATH ON THE PI
      device: /home/teresa/Music/music
      o: bind
